# Generated by Django 3.1.5 on 2021-03-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tora_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorjob',
            name='is_active',
            field=models.CharField(choices=[('0', '暂停'), ('1', '激活')], default='1', max_length=2, verbose_name='当前状态'),
        ),
    ]
