# Generated by Django 3.1.5 on 2021-09-09 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tora_monitor', '0003_diskmonitordata_downloadmonitorcfg_memmonitordata_nodetradeinfo_smscontroldata_smsrecorddata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DownloadMonitorCfg',
            new_name='ToraDatabaseMonitorCfg',
        ),
        migrations.AlterModelOptions(
            name='toradatabasemonitorcfg',
            options={'ordering': ['-id'], 'verbose_name': '奇点数据库日常监控项', 'verbose_name_plural': '奇点数据库日常监控项'},
        ),
    ]
