# Generated by Django 3.1.5 on 2021-09-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tora_monitor', '0004_auto_20210909_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toradatabasemonitorcfg',
            name='node_no',
            field=models.CharField(max_length=4, verbose_name='节点编号'),
        ),
        migrations.AlterUniqueTogether(
            name='toradatabasemonitorcfg',
            unique_together={('business', 'node_no')},
        ),
    ]
