# Generated by Django 3.1.5 on 2021-09-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tora_monitor', '0005_auto_20210914_1636'),
    ]

    operations = [
        migrations.CreateModel(
                name='FpgaMonitorData',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('inner_ip', models.GenericIPAddressField(verbose_name='内网IP')),
                    ('para_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='参数名称')),
                    ('para_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='参数类型')),
                    ('para_value', models.CharField(blank=True, max_length=254, null=True, verbose_name='参数值')),
                    ('bound', models.CharField(choices=[('0', '否'), ('1', '是')], default='1', max_length=2, verbose_name='是否约束')),
                    ('start_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='开始监控时间')),
                    ('end_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='开始监控时间')),
                    ('lower_limit', models.CharField(blank=True, max_length=20, null=True, verbose_name='阀值下限')),
                    ('upper_limit', models.CharField(blank=True, max_length=20, null=True, verbose_name='阀值上限')),
                    ('increment', models.CharField(choices=[('0', '否'), ('1', '是')], default='0', max_length=2, verbose_name='是否增长')),
                    ('is_warning', models.CharField(choices=[('0', '否'), ('1', '是')], default='0', max_length=2, verbose_name='是否需要报警')),
                    ('is_handled', models.CharField(choices=[('0', '否'), ('1', '是')], default='0', max_length=2, verbose_name='是否已处理')),
                    ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                    ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ],
                options={
                    'verbose_name': 'fpga监控数据',
                    'verbose_name_plural': 'fpga监控数据',
                },
            ),
            migrations.CreateModel(
                name='ipmiInfoData',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('ipmi_ip', models.GenericIPAddressField(verbose_name='管理口IP')),
                    ('cpu1_temp', models.FloatField(blank=True, max_length=40, null=True, verbose_name='cpu1温度')),
                    ('cpu2_temp', models.FloatField(blank=True, max_length=40, null=True, verbose_name='cpu2温度')),
                    ('cpu3_temp', models.FloatField(blank=True, max_length=40, null=True, verbose_name='cpu3温度')),
                    ('cpu4_temp', models.FloatField(blank=True, max_length=40, null=True, verbose_name='cpu4温度')),
                    ('fan1_sp', models.FloatField(blank=True, max_length=60, null=True, verbose_name='风扇1速度')),
                    ('fan2_sp', models.FloatField(blank=True, max_length=60, null=True, verbose_name='风扇2速度')),
                    ('fan3_sp', models.FloatField(blank=True, max_length=60, null=True, verbose_name='风扇3速度')),
                    ('fan4_sp', models.FloatField(blank=True, max_length=60, null=True, verbose_name='风扇4速度')),
                    ('fan5_sp', models.FloatField(blank=True, max_length=60, null=True, verbose_name='风扇5速度')),
                    ('fan6_sp', models.FloatField(blank=True, max_length=60, null=True, verbose_name='风扇6速度')),
                    ('fan7_sp', models.FloatField(blank=True, max_length=60, null=True, verbose_name='风扇7速度')),
                    ('fan8_sp', models.FloatField(blank=True, max_length=60, null=True, verbose_name='风扇8速度')),
                    ('fan9_sp', models.FloatField(blank=True, max_length=60, null=True, verbose_name='风扇9速度')),
                    ('fan10_sp', models.FloatField(blank=True, max_length=60, null=True, verbose_name='风扇10速度')),
                    ('fan11_sp', models.CharField(blank=True, max_length=60, null=True, verbose_name='风扇11速度')),
                    ('fan12_sp', models.FloatField(blank=True, max_length=60, null=True, verbose_name='风扇12速度')),
                    ('fan13_sp', models.FloatField(blank=True, max_length=60, null=True, verbose_name='风扇13速度')),
                    ('fan14_sp', models.FloatField(blank=True, max_length=60, null=True, verbose_name='风扇14速度')),
                    ('fan15_sp', models.FloatField(blank=True, max_length=60, null=True, verbose_name='风扇15速度')),
                    ('fan16_sp', models.FloatField(blank=True, max_length=60, null=True, verbose_name='风扇16速度')),
                    ('check_time', models.DateTimeField(blank=True, null=True, verbose_name='检测时间')),
                    ('baseline_flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='设为基准')),
                    ('origin_data', models.TextField(blank=True, null=True, verbose_name='原始数据')),
                ],
                options={
                    'verbose_name': 'IPMI硬件监控详情',
                    'verbose_name_plural': 'IPMI硬件监控详情',
                },
            ),
        migrations.RemoveField(
            model_name='diskmonitordata',
            name='total_disk',
        ),
        migrations.RemoveField(
            model_name='diskmonitordata',
            name='used_disk',
        ),
        migrations.AddField(
            model_name='diskmonitordata',
            name='avail_size',
            field=models.FloatField(default=0, max_length=20, verbose_name='可用量'),
        ),
        migrations.AddField(
            model_name='diskmonitordata',
            name='mounted_on',
            field=models.CharField(default='/', max_length=20, verbose_name='挂载盘'),
        ),
        migrations.AddField(
            model_name='diskmonitordata',
            name='total_size',
            field=models.FloatField(default=0, max_length=20, verbose_name='总量'),
        ),
        migrations.AddField(
            model_name='diskmonitordata',
            name='used_size',
            field=models.FloatField(default=0, max_length=20, verbose_name='已使用量'),
        ),
        migrations.AlterField(
            model_name='diskmonitordata',
            name='file_dir',
            field=models.CharField(default='/', max_length=40, verbose_name='目录'),
        ),
        migrations.AlterField(
            model_name='diskmonitordata',
            name='usage',
            field=models.FloatField(default=0, max_length=20, verbose_name='使用率%'),
        ),
        migrations.AlterField(
            model_name='memmonitordata',
            name='total_mem',
            field=models.FloatField(default=0, max_length=10, verbose_name='总内存'),
        ),
        migrations.AlterField(
            model_name='memmonitordata',
            name='usage',
            field=models.FloatField(default=0, max_length=10, verbose_name='已使用率%'),
        ),
        migrations.AlterField(
            model_name='memmonitordata',
            name='used_mem',
            field=models.FloatField(default=0, max_length=10, verbose_name='已使用量'),
        ),
    ]
