# Generated by Django 3.1.5 on 2021-09-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tora_monitor', '0006_auto_20210924_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskmonitordata',
            name='avail_size',
            field=models.FloatField(default=0, max_length=20, verbose_name='可用量(G)'),
        ),
        migrations.AlterField(
            model_name='diskmonitordata',
            name='is_handled',
            field=models.CharField(choices=[('0', '否'), ('1', '是')], default='0', max_length=2, verbose_name='是否已处理'),
        ),
        migrations.AlterField(
            model_name='diskmonitordata',
            name='is_warning',
            field=models.CharField(choices=[('0', '否'), ('1', '是')], default='0', max_length=2, verbose_name='是否需要报警'),
        ),
        migrations.AlterField(
            model_name='diskmonitordata',
            name='total_size',
            field=models.FloatField(default=0, max_length=20, verbose_name='总量(G)'),
        ),
        migrations.AlterField(
            model_name='diskmonitordata',
            name='usage',
            field=models.FloatField(default=0, max_length=20, verbose_name='使用率(%)'),
        ),
        migrations.AlterField(
            model_name='diskmonitordata',
            name='used_size',
            field=models.FloatField(default=0, max_length=20, verbose_name='已使用量(G)'),
        ),
        migrations.AlterField(
            model_name='memmonitordata',
            name='is_handled',
            field=models.CharField(choices=[('0', '否'), ('1', '是')], default='0', max_length=2, verbose_name='是否已处理'),
        ),
        migrations.AlterField(
            model_name='memmonitordata',
            name='is_warning',
            field=models.CharField(choices=[('0', '否'), ('1', '是')], default='0', max_length=2, verbose_name='是否需要报警'),
        ),
        migrations.AlterField(
            model_name='memmonitordata',
            name='total_mem',
            field=models.FloatField(default=0, max_length=10, verbose_name='总内存(G)'),
        ),
        migrations.AlterField(
            model_name='memmonitordata',
            name='usage',
            field=models.FloatField(default=0, max_length=10, verbose_name='已使用率(%)'),
        ),
        migrations.AlterField(
            model_name='memmonitordata',
            name='used_mem',
            field=models.FloatField(default=0, max_length=10, verbose_name='已使用量(G)'),
        ),
    ]
