# Generated by Django 3.1.5 on 2021-04-22 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toraapp', '0003_auto_20210421_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessApplyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inner_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='内网IP')),
                ('outer_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='互联网IP')),
                ('in_service_ports', models.GenericIPAddressField(blank=True, null=True, verbose_name='内部端口')),
                ('access_action', models.CharField(choices=[('0', '无'), ('1', '新增'), ('2', '移除')], default='0', max_length=2, verbose_name='网络授权')),
                ('behaviour', models.CharField(blank=True, choices=[('1', '放行'), ('2', '禁止')], default='1', max_length=2, null=True, verbose_name='行为')),
                ('direction', models.CharField(blank=True, choices=[('1', '内向外'), ('2', '外向内')], default='1', max_length=2, null=True, verbose_name='访问方向')),
                ('customer_ip', models.CharField(blank=True, max_length=200, null=True, verbose_name='客户外网地址')),
                ('customer_ports', models.CharField(blank=True, max_length=200, null=True, verbose_name='客户外网端口')),
                ('assigned_out_ip', models.CharField(blank=True, max_length=200, null=True, verbose_name='映射互联网地址')),
                ('assigned_out_ports', models.CharField(blank=True, max_length=200, null=True, verbose_name='映射互联网端口')),
                ('cur_status', models.CharField(choices=[('0', '待处理'), ('1', '完成'), ('2', '挂起'), ('8', '作废'), ('9', '失败')], default='1', max_length=2, verbose_name='当前状态')),
                ('comment', models.CharField(blank=True, max_length=254, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_cust', to='toraapp.toracustomer', verbose_name='使用客户')),
                ('operator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessadd_user', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_task', to='toraapp.taskflow', verbose_name='运维流水')),
            ],
            options={
                'verbose_name': '网络访问申请记录',
                'verbose_name_plural': '网络访问申请记录',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='ResourceApplyInfo',
        ),
    ]
