# Generated by Django 3.1.5 on 2021-04-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toraapp', '0004_auto_20210422_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessapplyinfo',
            name='behaviour',
            field=models.CharField(blank=True, choices=[('0', '放行'), ('1', '禁止')], default='0', max_length=2, null=True, verbose_name='行为'),
        ),
        migrations.AlterField(
            model_name='accessapplyinfo',
            name='direction',
            field=models.CharField(blank=True, choices=[('0', '内向外'), ('1', '外向内')], default='0', max_length=2, null=True, verbose_name='访问方向'),
        ),
        migrations.AlterField(
            model_name='globlepara',
            name='para_name',
            field=models.CharField(max_length=40, verbose_name='参数名称'),
        ),
        migrations.AlterField(
            model_name='globlepara',
            name='para_value',
            field=models.CharField(max_length=128, verbose_name='参数值'),
        ),
    ]
