# Generated by Django 3.1.5 on 2021-04-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toraapp', '0006_auto_20210430_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskflow',
            name='custgroup_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='客户组名'),
        ),
    ]
