# Generated by Django 3.1.5 on 2021-07-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toraapp', '0012_auto_20210606_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelfmachine',
            name='high_manager_ip',
        ),
        migrations.RemoveField(
            model_name='taskflow',
            name='high_manager_ip',
        ),
        migrations.AddField(
            model_name='shelfmachine',
            name='other_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='其他IP'),
        ),
        migrations.AddField(
            model_name='taskflow',
            name='other_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='其他IP'),
        ),
    ]
