# Generated by Django 3.1.5 on 2021-08-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toraapp', '0015_auto_20210810_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toracustomer',
            name='custgroup_name',
            field=models.CharField(blank=True, default='custgroup_name', max_length=100, null=True, verbose_name='客户组名'),
        ),
        migrations.AlterUniqueTogether(
            name='shelfmachine',
            unique_together=set(),
        ),
    ]
