# Generated by Django 3.1.5 on 2021-08-25 17:11

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('toraapp', '0016_auto_20210811_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upgradetask',
            options={'ordering': ['-id'], 'verbose_name': '00-奇点升级任务', 'verbose_name_plural': '00-奇点升级任务'},
        ),
        migrations.AlterField(
            model_name='shareserverinfo',
            name='is_active',
            field=models.CharField(choices=[('0', '不可用'), ('1', '正常'), ('4', '维修'), ('5', '空系统'), ('8', '已下架')], default='1', max_length=2, verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='shelfmachine',
            name='is_active',
            field=models.CharField(choices=[('0', '不可用'), ('1', '正常'), ('4', '维修'), ('5', '空系统'), ('8', '已下架')], default='1', max_length=2, verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='tradenode',
            name='app_type',
            field=models.CharField(choices=[('tradeserver1', '交易主-A线路'), ('tradeserver2', '交易备-A线路'), ('tradeserver1B', '交易主-B线路'), ('tradeserver2B', '交易备-B线路'), ('node_md_L1', '节点沪深L1行情'), ('trade_front1', '交易前置1'), ('trade_front2', '交易前置2'), ('trade_front3', '交易前置3'), ('mq_front1', '行情前置1'), ('mq_front2', '行情前置2'), ('mq_front3', '行情前置3'), ('fens1', 'fens1'), ('fens2', 'fens2'), ('fens3', 'fens3')], max_length=20, verbose_name='服务类型'),
        ),
        migrations.AlterField(
            model_name='upgradetask',
            name='comment',
            field=models.TextField(blank=True, max_length=254, null=True, verbose_name='升级备注'),
        ),
        migrations.AlterField(
            model_name='upgradetask',
            name='component',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('tradeserver1', '交易主-A线路'), ('tradeserver2', '交易备-A线路'), ('tradeserver1B', '交易主-B线路'), ('tradeserver2B', '交易备-B线路'), ('node_md_L1', '节点沪深L1行情'), ('trade_front1', '交易前置1'), ('trade_front2', '交易前置2'), ('trade_front3', '交易前置3'), ('mq_front1', '行情前置1'), ('mq_front2', '行情前置2'), ('mq_front3', '行情前置3'), ('fens1', 'fens1'), ('fens2', 'fens2'), ('fens3', 'fens3')], max_length=151, null=True, verbose_name='升级组件'),
        ),
    ]
