# Generated by Django 3.1.5 on 2021-08-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toraapp', '0017_auto_20210825_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeinfo',
            name='business',
            field=models.CharField(choices=[('hxzq', '现货股票'), ('sp', '期权'), ('rzrq', '两融'), ('qh', '期货')], default='hxzq', max_length=20, verbose_name='业务'),
        ),
        migrations.AddField(
            model_name='nodeinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
