# Generated by Django 3.1.5 on 2021-09-08 19:34

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('toraapp', '0019_auto_20210827_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nodecomponentinfo',
            options={'ordering': ['-id'], 'verbose_name': '03-节点详细信息', 'verbose_name_plural': '03-节点详细信息'},
        ),
        migrations.AlterModelOptions(
            name='upgradetask',
            options={'ordering': ['-id'], 'verbose_name': '00-升级任务', 'verbose_name_plural': '00-升级任务'},
        ),
        migrations.RenameField(
            model_name='tradenode',
            old_name='intnet_addr',
            new_name='internet_addr',
        ),
        migrations.RenameField(
            model_name='tradenode',
            old_name='intnet_port',
            new_name='internet_port',
        ),
        migrations.RemoveField(
            model_name='nodeinfo',
            name='mq',
        ),
        migrations.RemoveField(
            model_name='toramq',
            name='mq_group',
        ),
        migrations.AddField(
            model_name='nodeinfo',
            name='comment',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='shelfmachine',
            name='room_no',
            field=models.DateField(blank=True, max_length=50, null=True, verbose_name='房间号'),
        ),
        migrations.AddField(
            model_name='shelfmachine',
            name='row_no',
            field=models.DateField(blank=True, max_length=50, null=True, verbose_name='排编号'),
        ),
        migrations.AddField(
            model_name='toramq',
            name='node_nos',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='覆盖的节点'),
        ),
        migrations.AddField(
            model_name='toramq',
            name='register_type',
            field=models.CharField(choices=[('tcp', 'tcp注册'), ('multicast', 'multicast注册'), ('udp', 'upd注册')], default='tcp', max_length=20, verbose_name='注册方式'),
        ),
        migrations.AddField(
            model_name='toramq',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='toramqgroup',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='tradenode',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='nodecomponentinfo',
            name='business',
            field=models.CharField(choices=[('stock', '现货股票'), ('sp', '期权'), ('credit', '两融'), ('cffex', '中金期货')], max_length=20, verbose_name='业务'),
        ),
        migrations.AlterField(
            model_name='nodeinfo',
            name='business',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('stock', '现货股票'), ('sp', '期权'), ('credit', '两融'), ('cffex', '中金期货')], max_length=21, null=True, verbose_name='业务'),
        ),
        migrations.AlterField(
            model_name='nodeinfo',
            name='engine_room',
            field=models.CharField(choices=[('shwp', '上海宛平'), ('shgq', '上海外高桥'), ('shjq', '上海金桥'), ('shkj', '上海科技网'), ('shxt', '上海斜土路'), ('dgnf', '东莞南方')], max_length=10, verbose_name='机房'),
        ),
        migrations.AlterField(
            model_name='shareserverinfo',
            name='engine_room',
            field=models.CharField(choices=[('shwp', '上海宛平'), ('shgq', '上海外高桥'), ('shjq', '上海金桥'), ('shkj', '上海科技网'), ('shxt', '上海斜土路'), ('dgnf', '东莞南方')], max_length=10, verbose_name='机房'),
        ),
        migrations.AlterField(
            model_name='shelfmachine',
            name='engine_room',
            field=models.CharField(choices=[('shwp', '上海宛平'), ('shgq', '上海外高桥'), ('shjq', '上海金桥'), ('shkj', '上海科技网'), ('shxt', '上海斜土路'), ('dgnf', '东莞南方')], max_length=10, verbose_name='机房'),
        ),
        migrations.AlterField(
            model_name='systemuserinfo',
            name='engine_room',
            field=models.CharField(choices=[('shwp', '上海宛平'), ('shgq', '上海外高桥'), ('shjq', '上海金桥'), ('shkj', '上海科技网'), ('shxt', '上海斜土路'), ('dgnf', '东莞南方')], max_length=10, verbose_name='机房'),
        ),
        migrations.AlterField(
            model_name='taskflow',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='taskflow',
            name='engine_room',
            field=models.CharField(choices=[('shwp', '上海宛平'), ('shgq', '上海外高桥'), ('shjq', '上海金桥'), ('shkj', '上海科技网'), ('shxt', '上海斜土路'), ('dgnf', '东莞南方')], max_length=10, verbose_name='机房'),
        ),
        migrations.AlterField(
            model_name='toramq',
            name='business',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('stock', '现货股票'), ('sp', '期权'), ('credit', '两融'), ('cffex', '中金期货')], max_length=21, null=True, verbose_name='业务'),
        ),
        migrations.AlterField(
            model_name='toramqgroup',
            name='engine_room',
            field=models.CharField(choices=[('shwp', '上海宛平'), ('shgq', '上海外高桥'), ('shjq', '上海金桥'), ('shkj', '上海科技网'), ('shxt', '上海斜土路'), ('dgnf', '东莞南方')], max_length=10, verbose_name='机房'),
        ),
        migrations.AlterField(
            model_name='toraservice',
            name='business',
            field=models.CharField(choices=[('stock', '现货股票'), ('sp', '期权'), ('credit', '两融'), ('cffex', '中金期货')], max_length=20, verbose_name='业务'),
        ),
        migrations.AlterField(
            model_name='tradenode',
            name='app_type',
            field=models.CharField(choices=[('tradeserver1', '交易主高速A'), ('tradeserver2', '交易备高速A'), ('tradeserver1B', '交易主高速B'), ('tradeserver2B', '交易备高速B'), ('node_md_L1', '节点沪深L1行情'), ('trade_front1', '交易前置1'), ('trade_front2', '交易前置2'), ('trade_front3', '交易前置3'), ('trade_front4', '交易前置4'), ('mq_front1', '行情前置1'), ('mq_front2', '行情前置2'), ('mq_front3', '行情前置3'), ('fens1', 'fens1'), ('fens2', 'fens2'), ('fens3', 'fens3')], max_length=20, verbose_name='服务类型'),
        ),
        migrations.AlterField(
            model_name='tradenode',
            name='business',
            field=models.CharField(choices=[('stock', '现货股票'), ('sp', '期权'), ('credit', '两融'), ('cffex', '中金期货')], max_length=20, verbose_name='业务'),
        ),
        migrations.AlterField(
            model_name='upgradetask',
            name='business',
            field=models.CharField(choices=[('stock', '现货股票'), ('sp', '期权'), ('credit', '两融'), ('cffex', '中金期货')], max_length=20, verbose_name='业务'),
        ),
        migrations.AlterField(
            model_name='upgradetask',
            name='comment',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='upgradetask',
            name='component',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('tradeserver1', '主交易'), ('tradeserver2', '备交易'), ('node_md_L1', '节点沪深L1行情'), ('trade_front1', '交易前置1'), ('trade_front2', '交易前置2'), ('trade_front3', '交易前置3'), ('mq_front1', '行情前置1'), ('mq_front2', '行情前置2'), ('mq_front3', '行情前置3'), ('fens1', 'fens1'), ('fens2', 'fens2'), ('fens3', 'fens3')], max_length=123, null=True, verbose_name='升级组件'),
        ),
        migrations.AlterField(
            model_name='vpncfginfo',
            name='engine_room',
            field=models.CharField(choices=[('shwp', '上海宛平'), ('shgq', '上海外高桥'), ('shjq', '上海金桥'), ('shkj', '上海科技网'), ('shxt', '上海斜土路'), ('dgnf', '东莞南方')], max_length=10, verbose_name='机房'),
        ),
        migrations.AlterField(
            model_name='vpnuserinfo',
            name='engine_room',
            field=models.CharField(choices=[('shwp', '上海宛平'), ('shgq', '上海外高桥'), ('shjq', '上海金桥'), ('shkj', '上海科技网'), ('shxt', '上海斜土路'), ('dgnf', '东莞南方')], max_length=10, verbose_name='机房'),
        ),
    ]
