# Generated by Django 3.1.5 on 2021-09-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toraapp', '0020_auto_20210908_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradenode',
            name='internet_addr',
        ),
        migrations.RemoveField(
            model_name='tradenode',
            name='internet_port',
        ),
        migrations.AddField(
            model_name='tradenode',
            name='internet_addr_ports',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='互联网地址端口'),
        ),
        migrations.AlterField(
            model_name='toramq',
            name='mq_type',
            field=models.CharField(choices=[('md_L2', '沪深行情L2'), ('md_L1', '沪深行情L1'), ('sse_md_L2', '沪市行情L2'), ('szse_md_L2A', '深市行情L2'), ('szse_md_L2B', '深市行情fpga_L2_B'), ('szse_md_L2C', '深市行情fpga_L2_C'), ('cffex_L1', '期货行情L1')], max_length=20, verbose_name='行情类型'),
        ),
    ]
