# Generated by Django 3.1.5 on 2021-09-09 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toraapp', '0021_auto_20210909_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeDetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(choices=[('stock', '现货股票'), ('sp', '期权'), ('credit', '两融'), ('cffex', '中金期货')], max_length=20, verbose_name='业务')),
                ('ip_addr', models.CharField(max_length=40, verbose_name='地址')),
                ('component', models.CharField(blank=True, max_length=100, null=True, verbose_name='组件')),
                ('port', models.CharField(blank=True, max_length=40, null=True, verbose_name='端口')),
                ('current_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='当前版本')),
                ('api_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='api版本')),
                ('upgrade_time', models.DateTimeField(blank=True, null=True, verbose_name='升级时间')),
                ('last_back_dir', models.CharField(blank=True, max_length=100, null=True, verbose_name='最新备份目录')),
                ('back_time', models.DateTimeField(blank=True, null=True, verbose_name='备份时间')),
                ('sys_status', models.CharField(blank=True, choices=[('0', '异常'), ('1', '正常'), ('2', '升级中'), ('3', '回退中'), ('4', '其他')], max_length=10, null=True, verbose_name='当前状态')),
                ('monitor_time', models.DateTimeField(blank=True, null=True, verbose_name='监控时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_node', to='toraapp.nodeinfo', verbose_name='节点编号')),
                ('operator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp_add_user', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '03-节点详细信息',
                'verbose_name_plural': '03-节点详细信息',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='NodeComponentInfo',
        ),
    ]
