# Generated by Django 3.1.5 on 2021-09-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toraapp', '0024_auto_20210910_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfmachine',
            name='room_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='房间号'),
        ),
        migrations.AlterField(
            model_name='shelfmachine',
            name='row_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='排编号'),
        ),
    ]
