# Generated by Django 3.1.5 on 2021-09-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toraapp', '0025_auto_20210913_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodedetailinfo',
            name='api_version',
        ),
        migrations.AlterField(
            model_name='nodedetailinfo',
            name='current_version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='当前系统版本'),
        ),
    ]
