# Generated by Django 3.1.5 on 2021-09-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toraapp', '0026_auto_20210913_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodedetailinfo',
            name='ip_addr',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='地址'),
        ),
    ]
