# Generated by Django 3.1.5 on 2021-09-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toraapp', '0027_auto_20210913_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toracustomer',
            name='custgroup_name',
            field=models.CharField(default='custgroup_name', max_length=100, verbose_name='客户组名'),
        ),
    ]
