# Generated by Django 3.1.5 on 2021-09-14 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toraapp', '0028_auto_20210913_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareserverinfo',
            name='share_type',
            field=models.CharField(choices=[('1', '客户独用'), ('2', '客户共用'), ('3', '华鑫奇点自用'), ('9', '不确定')], max_length=2, verbose_name='共享类型'),
        ),
        migrations.AlterField(
            model_name='shelfmachine',
            name='assert_type',
            field=models.CharField(choices=[('1', '实体服务器'), ('2', '虚拟机'), ('3', '云服务器'), ('4', '交换机'), ('5', '光分器'), ('9', '其他')], default='1', max_length=2, verbose_name='资产类型'),
        ),
        migrations.AlterField(
            model_name='shelfmachine',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_node', to='toraapp.nodeinfo', verbose_name='节点编号'),
        ),
        migrations.AlterField(
            model_name='shelfmachine',
            name='purpose',
            field=models.CharField(choices=[('1', '客户独用'), ('2', '客户共用'), ('3', '华鑫奇点自用'), ('9', '不确定')], default='1', max_length=2, verbose_name='使用方式'),
        ),
        migrations.AlterField(
            model_name='taskflow',
            name='assert_type',
            field=models.CharField(choices=[('1', '实体服务器'), ('2', '虚拟机'), ('3', '云服务器'), ('4', '交换机'), ('5', '光分器'), ('9', '其他')], default='1', max_length=2, verbose_name='资产类型'),
        ),
        migrations.AlterField(
            model_name='taskflow',
            name='purpose',
            field=models.CharField(choices=[('1', '客户独用'), ('2', '客户共用'), ('3', '华鑫奇点自用'), ('9', '不确定')], default='9', max_length=2, verbose_name='使用方式'),
        ),
    ]
