# Generated by Django 3.1.5 on 2021-09-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toraapp', '0029_auto_20210914_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodedetailinfo',
            name='current_version',
            field=models.CharField(default='1.0', max_length=100, verbose_name='当前系统版本'),
        ),
    ]
