# Generated by Django 3.1.5 on 2021-09-24 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toraapp', '0030_auto_20210915_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareserverinfo',
            name='share_type',
            field=models.CharField(choices=[('1', '客户独用'), ('2', '客户共用'), ('3', '奇点自用'), ('4', '全创其他项目组'), ('5', '华鑫证券独用'), ('9', '不确定')], max_length=2, verbose_name='共享类型'),
        ),
        migrations.AlterField(
            model_name='shelfmachine',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='machine_node', to='toraapp.nodeinfo', verbose_name='节点编号'),
        ),
        migrations.AlterField(
            model_name='shelfmachine',
            name='purpose',
            field=models.CharField(choices=[('1', '客户独用'), ('2', '客户共用'), ('3', '奇点自用'), ('4', '全创其他项目组'), ('5', '华鑫证券独用'), ('9', '不确定')], default='1', max_length=2, verbose_name='使用方式'),
        ),
        migrations.AlterField(
            model_name='taskflow',
            name='purpose',
            field=models.CharField(choices=[('1', '客户独用'), ('2', '客户共用'), ('3', '奇点自用'), ('4', '全创其他项目组'), ('5', '华鑫证券独用'), ('9', '不确定')], default='9', max_length=2, verbose_name='使用方式'),
        ),
    ]
