# Generated by Django 3.1.5 on 2021-09-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toraapp', '0031_auto_20210924_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toracustomer',
            name='custgroup_name',
            field=models.CharField(blank=True, default='custgroup_name', max_length=100, null=True, verbose_name='客户组名'),
        ),
        migrations.AlterField(
            model_name='vpnuserinfo',
            name='vpn_phone',
            field=models.CharField(default='', max_length=40, verbose_name='vpn注册手机号'),
        ),
    ]
