# Generated by Django 3.1.5 on 2021-02-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True, verbose_name='任务标识')),
                ('trigger', models.CharField(choices=[('date', '一次性'), ('interval', '固定间隔'), ('cron', 'crontab格式')], default='cron', max_length=20, verbose_name='触发类型')),
                ('job_func', models.CharField(max_length=40, verbose_name='任务函数')),
                ('job_args', models.CharField(blank=True, max_length=40, null=True, verbose_name='任务参数')),
                ('month', models.CharField(blank=True, max_length=40, null=True, verbose_name='月(1-12)')),
                ('day', models.CharField(blank=True, max_length=40, null=True, verbose_name='日(1-31)')),
                ('week', models.CharField(blank=True, max_length=40, null=True, verbose_name='周(1-53)')),
                ('day_of_week', models.CharField(blank=True, max_length=40, null=True, verbose_name=' 周内第几天或者星期几')),
                ('hour', models.CharField(blank=True, max_length=40, null=True, verbose_name=' 小时')),
                ('minute', models.CharField(blank=True, max_length=40, null=True, verbose_name='分')),
                ('second', models.CharField(blank=True, max_length=40, null=True, verbose_name='秒')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='最早开始日期')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='最晚结束日期')),
                ('is_active', models.CharField(choices=[('0', '未激活'), ('1', '正常')], default='1', max_length=2, verbose_name='启用状态')),
                ('comment', models.CharField(blank=True, max_length=254, null=True, verbose_name='任务说明')),
                ('last_status', models.CharField(blank=True, max_length=40, null=True, verbose_name='最新监控结果')),
                ('last_runtime', models.DateTimeField(blank=True, null=True, verbose_name='最后执行时间')),
                ('monitor_data', models.TextField(blank=True, null=True, verbose_name='监控返回数据')),
            ],
            options={
                'verbose_name': '监控任务',
                'verbose_name_plural': '监控任务',
            },
        ),
    ]
