version: 1
disable_existing_loggers: False
formatters:
    brief:
        format: "%(asctime)s - %(message)s"
    simple:
        format: "%(asctime)s - %(filename)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: brief
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: INFO
        formatter: simple
        filename: ./mylog/check_xwdm_run.log
        backupCount: 20
        encoding: utf8
        when: MIDNIGHT

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: ./mylog/check_xwdm_errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    main.mssql_tools:
        level: INFO
        handlers: [console, info_file_handler,error_file_handler]
        propagate: no

root:
    level: INFO
    handlers: [console, info_file_handler,error_file_handler]