# Generated by Django 3.1.5 on 2021-04-14 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toraapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeinfo',
            name='mq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_mq', to='toraapp.toramqgroup', verbose_name='对应行情组'),
        ),
    ]
