# Generated by Django 3.1.5 on 2021-04-21 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toraapp', '0002_auto_20210414_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareserverinfo',
            name='comment',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='shelfmachine',
            name='rsa_users',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='免密账号'),
        ),
        migrations.CreateModel(
            name='GloblePara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para_name', models.CharField(max_length=20, verbose_name='参数名称')),
                ('para_value', models.CharField(max_length=20, verbose_name='参数值')),
                ('comment', models.CharField(blank=True, max_length=254, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('modify_oper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paramodify_user', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
                ('operator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='paraadd_user', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '全局参数设置',
                'verbose_name_plural': '全局参数设置',
                'ordering': ['-id'],
            },
        ),
    ]
