# Generated by Django 3.1.5 on 2021-04-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toraapp', '0005_auto_20210429_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuserinfo',
            name='nsight_user',
        ),
        migrations.RemoveField(
            model_name='vpnuserinfo',
            name='nsight_user',
        ),
        migrations.AlterField(
            model_name='toracustomer',
            name='custgroup_name',
            field=models.CharField(blank=True, default='nsigt_user', max_length=100, null=True, verbose_name='客户组名'),
        ),
        migrations.AlterUniqueTogether(
            name='toracustomer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='toracustomer',
            name='nsight_user',
        ),
    ]
