# Generated by Django 3.1.5 on 2021-04-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toraapp', '0007_auto_20210430_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskflow',
            name='is_new_vpn',
            field=models.CharField(choices=[('0', '否'), ('1', '是')], max_length=10, verbose_name='是否新分配vpn'),
        ),
        migrations.AlterField(
            model_name='taskflow',
            name='vpn_phone',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='vpn注册手机号'),
        ),
        migrations.AlterField(
            model_name='taskflow',
            name='vpn_user_name',
            field=models.CharField(max_length=254, verbose_name='vpn用户名'),
        ),
    ]
