# Generated by Django 3.1.5 on 2021-05-06 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toraapp', '0008_auto_20210430_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='toracustomer',
            name='vpn_user_name',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='vpn用户名'),
        ),
        migrations.AlterField(
            model_name='taskflow',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_cust', to='toraapp.toracustomer', verbose_name='使用客户'),
        ),
        migrations.AlterField(
            model_name='toracustomer',
            name='phone',
            field=models.CharField(max_length=254, verbose_name='手机号'),
        ),
    ]
