# Generated by Django 3.1.5 on 2021-05-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toraapp', '0009_auto_20210506_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskflow',
            name='is_new_vpn',
            field=models.CharField(max_length=10, verbose_name='是否新分配vpn(格式：1;0;1最多设置5个)'),
        ),
    ]
