# Generated by Django 3.1.5 on 2021-06-06 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toraapp', '0010_auto_20210513_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeinfo',
            name='cust_mail_module',
            field=models.TextField(blank=True, null=True, verbose_name='客户邮件模板信息'),
        ),
        migrations.AlterField(
            model_name='shelfmachine',
            name='cpu_model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='cpu型号'),
        ),
        migrations.CreateModel(
            name='VpnCfgInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_room', models.CharField(choices=[('shwp', '上海宛平'), ('shnq', '上海宁桥'), ('shgq', '上海外高桥'), ('shjq', '上海金桥'), ('shkj', '上海科技网'), ('shxt', '上海斜土路'), ('dgnf', '东莞南方')], max_length=10, verbose_name='机房')),
                ('vpn_address', models.CharField(max_length=40, verbose_name='vpn连接地址')),
                ('vpn_init_passwd', models.CharField(max_length=40, verbose_name='vpn初始密码')),
                ('comment', models.CharField(blank=True, max_length=254, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vpncfg_oper', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '91-vpn配置信息',
                'verbose_name_plural': '91-vpn配置信息',
                'ordering': ['-id'],
            },
        ),
    ]
