# Generated by Django 3.1.5 on 2021-08-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toraapp', '0013_auto_20210727_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfmachine',
            name='shelf_date',
            field=models.DateField(blank=True, null=True, verbose_name='上架时间'),
        ),
    ]
