# Generated by Django 3.1.5 on 2021-08-10 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toraapp', '0014_shelfmachine_shelf_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vpncfginfo',
            options={'ordering': ['-id'], 'verbose_name': '81-vpn配置信息', 'verbose_name_plural': '81-vpn配置信息'},
        ),
        migrations.AlterField(
            model_name='nodeinfo',
            name='mq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_mq', to='toraapp.toramqgroup', verbose_name='对应行情组'),
        ),
        migrations.AlterField(
            model_name='shelfmachine',
            name='is_monitor',
            field=models.CharField(choices=[('0', '否'), ('1', '是')], default='0', max_length=2, verbose_name='是否监控'),
        ),
        migrations.AlterField(
            model_name='shelfmachine',
            name='other_ip',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='其他IP'),
        ),
        migrations.AlterField(
            model_name='taskflow',
            name='other_ip',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='其他IP'),
        ),
    ]
